# Generated by Django 5.0.2 on 2024-02-17 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalworldPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting objects.', verbose_name='active')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('player_uid', models.CharField(max_length=255, unique=True)),
                ('steam_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Palworld Player',
                'verbose_name_plural': 'Palworld Players',
                'db_table': 'palworld_players',
            },
        ),
    ]
